### ISSUE TITLE
Support for user-specified CPU type

### ISSUE THREAD

**Issue by dmclark17** [NWChemEx-Project/CMakeBuild#94]
I have a workflow where I am compiling TAMM on a build system and then running it on a node with a different CPU type. It looks like `-march=native` is used in a couple places to compile TAMM's dependencies. Would it be possible to add a cmake variable that allows users to specify the CPU type?

Thanks!

**Comment by twindus** [comment]
@ajaypanyala Is this something that we should keep open?  At some point, it would be good to get TAMM building using CMakePP.

**Comment by ajaypanyala** [comment]
I have what David asked for in a branch at the moment, will merge it into `master` soon and close this issue then.

**Comment by ajaypanyala** [comment]
Fixed in [#fd2936d](https://github.com/NWChemEx-Project/CMakeBuild/commit/fd2936d11ee9b3045e6b43c4e4b7e1e47c149da4)
